//state
export const state = {
  items: [
    {
      id: '001-beetroot',
      name: 'beetroot',
      img: String.raw`assets/icons/001-beetroot.svg`,
      price: 0.35,
      type: 'vegetable',
    },
    {
      id: '002-carrot',
      name: 'carrot',
      img: String.raw`assets/icons/002-carrot.svg`,
      price: 0.35,
      type: 'vegetable',
    },
    {
      id: '003-apple',
      name: 'apple',
      img: String.raw`assets/icons/003-apple.svg`,
      price: 0.35,
      type: 'fruit',
    },
    {
      id: '004-apricot',
      name: 'apricot',
      img: String.raw`assets/icons/004-apricot.svg`,
      price: 0.35,
      type: 'fruit',
    },
    {
      id: '005-avocado',
      name: 'avocado',
      img: String.raw`assets/icons/005-avocado.svg`,
      price: 0.35,
      type: 'vegetable',
    },
    {
      id: '006-bananas',
      name: 'bananas',
      img: String.raw`assets/icons/006-bananas.svg`,
      price: 0.35,
      type: 'fruit',
    },
    {
      id: '007-bell-pepper',
      name: 'bell pepper',
      img: String.raw`assets/icons/007-bell-pepper.svg`,
      price: 0.35,
      type: 'vegetable',
    },
    {
      id: '008-berry',
      name: 'berry',
      img: String.raw`assets/icons/008-berry.svg`,
      price: 0.35,
      type: 'fruit',
    },
    {
      id: '009-blueberry',
      name: 'blueberry',
      img: String.raw`assets/icons/009-blueberry.svg`,
      price: 0.35,
      type: 'fruit',
    },
    {
      id: '010-eggplant',
      name: 'eggplant',
      img: String.raw`assets/icons/010-eggplant.svg`,
      price: 0.35,
      type: 'vegetable',
    },
  ],
  cart: [],
};
